# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-05-22 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_list', '0002_movie_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-pub_date']},
        ),
    ]
